### ISSUE TITLE
Realtek drivers do not reach maximum advertised speed as AP

### ISSUE THREAD

**Issue by yagoplx** [lwfinger/rtl8192ee#1]
Wonder what could be causing this? Seems to affect all realtek drivers.

8192eu case: https://github.com/Mange/rtl8192eu-linux-driver/issues/150

Got my 8192ee some high gain antennas, put it on a empty channel, and loaded up the speedtest on the phone. Iwconfig reports bitrate at 300 properly, but actual download speed on the phone never rises higher than 50Mbps. This is on wireless N, 40MHz and 20MHz show no difference.

RX STBC1 is on as well

Perhaps looking into this could shed some light on improving the performance of rtlwifi drivers.

**Comment by lwfinger** [comment]
Obviously, the drivers are improperly coded. As you have the source and have identified the problem, please be my guest and fix it. I do not have (1) the knowledge, or (2) the desire. Obviously, #1 could be overcome, but not #2. I will gladly merge any "fixes" you find!

**Comment by yagoplx** [comment]
Considering the source is a complete mess of "RTL_IEEE_80211_ARGS_RF_EU_JARGON_2GHZ_A" and lines alike

It is likely no one has #2, not even the enginner that gets paid to write it.
Either way he/she's probably the only one who can understand the code, when considering tasks more complex than adding a device or two to the driver.

Realtek support on Linux is grim indeed.
