### ISSUE TITLE
Driver will not compile if you enable bluetooth coexistence.

### ISSUE THREAD

**Issue by yagoplx** [lwfinger/rtl8192ee#11]
Set CONFIG_BT_COEXIST in Makefile to y (it is set at n by default) to build in btcoexist. However the compilation hangs up at a single line. (rtl8192ee/hal/hal_btcoex.c:2591:2:)

```/home/safe/Development/rtl8192ee/hal/hal_btcoex.c:2591:2: error: implicit declaration of function ‘rtw_init_timer’; did you mean ‘rtw_init_netdev’? [-Werror=implicit-function-declaration]
 2591 |  rtw_init_timer(&GLBtcBtMpOperTimer, padapter, _btmpoper_timer_hdl, pBtCoexist);
      |  ^~~~~~~~~~~~~~
      |  rtw_init_netdev
```
Commenting out the line lets it compile, but I doubt that is the intended behaviour.

**Comment by lwfinger** [comment]
There are nearly 10 other instances of what needs to be done to fix rtw_init_timer() for kernels newer than 4.15 in the driver. I will do this, but not immediately as I have more pressing problems.

**Comment by lwfinger** [comment]
That one is fixed and it will now compile; however, there is a ton of code that has never been executed before. Good luck.

**Comment by yagoplx** [comment]
I shall test it and if all is good include it by default in the driver.

**Comment by yagoplx** [comment]
Testing reveals this just makes the driver crap itself near a bluetooth device, and just starts dropping packets forever. I'm submitting a PR to remove this from the makefile before anyone tries to use it.
