### ISSUE TITLE
Power transmission not increasing even after changing code

### ISSUE THREAD

**Issue by AbhasKr** [lwfinger/rtl8192ee#18]
I manually changed the file "hal/rl8192e/rtl8192e_phycfg.c". Changes to the code made :
int transmit_power_override = 20;

However the power transmission is still coming as 12dB, which is the minimum. Are there any other changes required to increase the power ?

**Comment by lwfinger** [comment]
Probably; however, this driver is not supported. As long as it builds, what you see is what you get. Of you find the solution, I will be happy to merge the changes, but I will not devote any time to fixing the problem.

**Comment by yagoplx** [comment]
The number it reports, 12db, is hardcoded. Nobody has actually made the driver report txpower yet. But that code does in fact change the txpower, you just won't see it on the system tools.

**Comment by yagoplx** [comment]
Addressed in https://github.com/lwfinger/rtl8192ee/pull/20
