### ISSUE TITLE
Unable to compile module on 5.10.15

### ISSUE THREAD

**Issue by Linuxxer2019** [lwfinger/rtl8192ee#23]
I am using Linux system running kernel 5.4 and 5.10 series. Module get compile for 5.4 series kernel. But having issue with 5.10 series. 

Please check the error log.

[MAKELOG.TXT](https://github.com/lwfinger/rtl8192ee/files/5977892/MAKELOG.TXT)

**Comment by lwfinger** [comment]
The source is updated for that kernel change and will now build for kernels through 5.11 (at least). Thanks for the report.
