### ISSUE TITLE
Fatal errors during make

### ISSUE THREAD

**Issue by JonathanLS** [lwfinger/rtl8192ee#24]
Hello, lwfinger! **Thank you f**or sharing your work with others.

May you help me with this? I am facing the fatal errors below during make.

make: "/rtl8192ee/Makefile" line 1864: warning: duplicate script for target "ifneq" ignored
make: "/rtl8192ee/Makefile" line 1840: warning: using previous script for "ifneq" defined here
make: "/rtl8192ee/Makefile" line 1864: warning: duplicate script for target "(,)" ignored
make: "/rtl8192ee/Makefile" line 1840: warning: using previous script for "(,)" defined here
make: "/rtl8192ee/Makefile" line 1865: warning: duplicate script for target "ifneq" ignored
make: "/rtl8192ee/Makefile" line 1840: warning: using previous script for "ifneq" defined here
make: "/rtl8192ee/Makefile" line 1865: warning: duplicate script for target "(,)" ignored
make: "/rtl8192ee/Makefile" line 1840: warning: using previous script for "(,)" defined here
make: "/rtl8192ee/Makefile" line 1866: Need an operator
make: "/rtl8192ee/Makefile" line 1891: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /rtl8192ee

**WHAT I DID:**

- I've downloaded the repository using GIT.
- I've executed GIT PULL.
- I've tried "make clean"

**WHAT IS MY KERNEL:**

FreeBSD 12.2-RELEASE r366954 GENERIC amd64

**WHAT I NEED TO DO:**

I am running a Firewall pfSense 2.5.0-RELEASE (amd64) built on Tue Feb 16 08:56:29 EST 2021 FreeBSD 12.2-STABLE.

It's a RTL8192EE adapter installed, but I can't get its driver attached on boot. I've tried RTWN, but it didn't work, so I was trying use your repository. I am using a Virtual Machine running FreeBSD 12.2-RELEASE to compile the drivers. After compiled them I move the files to pfSense.

You can find more detials here [https://forum.netgate.com/topic/161257/rtl8192ee-pcie-wireless-network-adapter-chip-0x818b10ec/1](url)

**Comment by lwfinger** [comment]
The driver is for Linux, not FreeBSD. Some of the drivers came from Realtek with FreeBSD options, but not this one.
