### ISSUE TITLE
Support for kernel 5.11 series

### ISSUE THREAD

**Issue by a-ozkan** [lwfinger/rtl8192ee#26]
Hi.
The driver does not work on the kernel version 5.11 series. 
Successfully builded and loaded, but not work.
Kernel: Arch Linux Zen 5.11
Build method: DKMS

**Comment by lwfinger** [comment]
How am I supposed to know why it doesn't work? You provide no logs of any failure!

**Comment by a-ozkan** [comment]
Sorry.
Journalctl outputs here.

[log-5.11-kernel.txt](https://github.com/lwfinger/rtl8192ee/files/6330776/log-5.11-kernel.txt)
[log-5.11-lwfinger.txt](https://github.com/lwfinger/rtl8192ee/files/6330777/log-5.11-lwfinger.txt)

**Comment by lwfinger** [comment]
I do not know why you closed this, but neither log shows any problem. The rtl8192ee device was renamed to wlan1, which means all was OK. Apparently your user-space part of wifi control never did anything.
