### ISSUE TITLE
Problem for compiling 

### ISSUE THREAD

**Issue by kayarec** [lwfinger/rtl8192ee#27]
Hi.

I've got a problem for compiling on debain bullseye : 
sudo make all
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.0-6-amd64/build M=/home/kayarec/rtl8192ee  modules
make[1]: *** /lib/modules/5.10.0-6-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:1823: modules] Error 2

Will you update the kernel library ? or is it an other problem ?

My kernel is :
Linux  5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux

Thanks

**Comment by lwfinger** [comment]
You have not installed the kernel headers. Consult Debian's website for instructions.

**Comment by kayarec** [comment]
Thanks
Everything is working great : compil, install, blacklist and boot 
So the module is recognized by the system
