### ISSUE TITLE
Driver for opensuse Leap 15.3 failed

### ISSUE THREAD

**Issue by Linuxxer2019** [lwfinger/rtl8192ee#28]
Unable to build module on opensuse.

[make.log](https://github.com/lwfinger/rtl8192ee/files/6642726/make.log)

Thanks in advance.

**Comment by lwfinger** [comment]
The problem was that openSUSE 15.3 backported some changes from later kernels. That missing item should have been in kernels through 5.7. I do not usually do this, but I added a quirk that recognizes Leap 15.3 and adjusts the code.

Do a 'git pull' and it should build.

**Comment by Linuxxer2019** [comment]
Thanks. It is working now.
