### ISSUE TITLE
Any new updates from Realtek?

### ISSUE THREAD

**Issue by yagoplx** [lwfinger/rtl8192ee#7]
Could you ask Realtek if they have a newer version of this beta private driver? (and then upload it here) I am interested in what performance improvements they could have made.

My wireless router has been working very well with this driver since I finished the scripts controlling the network and any quirks I noticed on my trials.

I have just now retried the rtlwifi_new driver, but it is not yet fit for this application. Yet, there seems to be advancements being made. Great work, keep it up.

**Comment by yagoplx** [comment]
Thanks for the 5.6 revision!

**Comment by yagoplx** [comment]
bump.
Is it just me or is this specific chip abandoned because of its low cost :|

**Comment by lwfinger** [comment]
Why do you think anyone reading this would have any knowledge of Realtek's plans. They abandon manufacture of chips because they have a cheaper design, a faster design, or who knows?

There are no newer drivers. Their developers are working on newer chips.

**Comment by yagoplx** [comment]
Well, rip. Not sure what I was expecting (trying my luck?), but this is indeed a low-end BGN wifi adapter. makes sense to abandon it from a financial standpoint at this point.
